# ======================
# Configuration de Tinnu
# ======================

# Activation ou désactivation du plugin
plugin-actif: false

# Position du soleil au début du jour
position-soleil-jour: 22570

# Position du soleil au début de la nuit
position-soleil-nuit: 13200

# Heure de lever du soleil
heure-lever-soleil: "06:00"

# Heure de coucher du soleil
heure-coucher-soleil: "18:00"

# Liste des mondes pris en charge par le plugin
mondes-supportes:
  - world

# Nombre de fois où l'heure est modifié dans un cycle de jour ou de nuit
nb-repostionnements: 20


